### PR TITLE
Donation

### PR DESCRIPTION
**Pull request by Brack0**
Hey @darahak :wave: 

Some translations for donate_page.
I'll add commits for other parts of that page in this pull request.

Trivia : I got a pretty rough time to run `npm install` (due to sharp).

### CODE REVIEW

**Comment by darahak** [comment]
Thanks @Brack0!
I converted it to a draft while you work on it. Feel free to re-open it when you're done.

**Comment by Brack0** [comment]
You can take FAQ if you have time, i'm not working on it right now

**Comment by darahak** [comment]
> You can take FAQ if you have time, i'm not working on it right now

I'll take care of the FAQ.

**Comment by darahak** [comment]
I didn't see there were a few blocks left before merging.
I can finish the doc if you're not working on it either.

**Pull request merged**
